language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-shapely

install:
  - pip install .

script: "cd tests; python trimesh_tests.py"

notifications:
    email: false