language: python
sudo: required
dist: trusty
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_deploy:
- sudo apt-get install pandoc -y
- pip install pypandoc
- pip install -r docs/requirements.txt
- python docs/build.py
deploy:
- provider: pypi
  user: mikedh
  on:
    python: '3.6'
    branch: master
  password:
    secure: MmFES9M+UZbfpQsWeSVlhgUcdbpCymaeJwExxcyJbkKKWdRoZLRusqCmTdQ7Rai8DxH++ooqgEnHwq+D9e/8Y0jbbFBScPbJVeNFj1B4xV36NlyV8A0027/UTuhvkhoUv/xP6mN4TfuC3tWEj5m20DQlibjjxS154r/BlA6/kic=
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  target-branch: gh-pages
  local-dir: docs/html
  on:
    python: '3.6'
    branch: master
before_install:
- sudo apt-get update
- sudo apt-get install -y openscad blender meshlab xvfb
- sudo wget https://github.com/mikedh/v-hacd-1/raw/master/bin/linux/testVHACD --quiet
  -P /usr/bin
- sudo chmod +x /usr/bin/testVHACD
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget --quiet https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy
- source activate test-environment
- pip install .
- pip install nose2
script:
- python -c "import trimesh"
- conda install scikit-image rtree shapely
- if [[ "$TRAVIS_PYTHON_VERSION" != "3.3" && "$TRAVIS_PYTHON_VERSION" != "3.4" ]];
  then conda install pyembree && pip install python-fcl; fi
- pip install .[easy]
- pip install xxhash
- cd tests
- nose2
- cd ../examples
- for f in *.ipynb; do python ../tests/notebook_run.py exec "$f"; done
- cd ..
