[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools >= 40.8",
    "wheel",
]

[tool.ruff]
select = ["E", "F", # the default rules
          "T201",   # disallow print statements
	  "B",      # pass bugbear
          "I001",   # isort
          "D"]      # pydocstyle
ignore = ["B905"] # `zip()` without an explicit `strict=`
line-length = 90


[tool.ruff.pydocstyle]
convention = "numpy"